---
- name: Install git and ruby dependencies
  apt: update_cache=yes pkg={{ item }} state=present
  sudo: yes
  with_items:
          - git-core
          - build-essential
          - zlib1g-dev
          - libreadline-dev
          - libssl-dev
          - libcurl4-openssl-dev
          - libmysql-ruby
          - libmysqlclient-dev


- name: Install rbenv  locally
  sudo_user: "{{ user }}"
  sudo: yes
  git: repo=git://github.com/sstephenson/rbenv.git  dest="{{ rbenv_dir }}"

- name:  Install ruby-build plugin
  sudo_user: "{{ user }}"
  sudo: yes
  git: repo=git://github.com/sstephenson/ruby-build.git  dest="{{ rbenv_plugins }}/ruby-build"
 
- name: Touch your shell configuration file in case does not exist
  command: "/usr/bin/touch  {{home}}/.{{ sh }}rc"

- name: Add rbenv to path in your shell configuration file
  sudo_user: "{{ user }}"
  sudo: yes
  lineinfile: dest="{{ home }}/.{{ sh }}rc" line="export PATH=$HOME/.rbenv/bin:$PATH" state=present

- name: Custom .gemrc 
  copy: src=gemrc dest="{{ home }}/.gemrc" owner="{{ user }}" group="{{ user }}" mode=0645

- name: Custom .irbrc
  copy: src=irbrc dest="{{ home }}/.irbrc" owner="{{ user }}" group="{{ user }}" mode=0644

- name: Eval rbenv init
  sudo_user: "{{ user }}"
  sudo: yes
  lineinfile: dest="{{ home }}/.{{ sh }}rc" line="eval \"$(rbenv init -)\" " state=present

- name: Install ruby version
  sudo_user: "{{ user }}"
  sudo: yes
  command: "{{rbenv_dir}}/bin/rbenv install {{ ruby_version }} -f"
  when: ruby_version is defined

- name: Enable ruby global version
  sudo_user: "{{ user }}"
  sudo: yes
  command: "{{rbenv_dir}}/bin/rbenv global {{ ruby_version }}"
  when: ruby_version is defined

